name: Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release: 
    types: [ published ]
      
      
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GITHUB_FEED: https://nuget.pkg.github.com/clinia/
  GITHUB_USER: clinia-ci
  GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ ubuntu-20.04, windows-latest, macos-latest ]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Test
        run: dotnet test -c Release --no-restor
        
      - name: Find Versions
        id: version
        if: matrix.os == 'ubuntu-20.04'
        uses: oprypin/find-latest-tag@v1
        with:
          repository: clinia/dotnet-extensions
          releases-only: true
        
      - name: Pack
        if: matrix.os == 'ubuntu-20.04'
        run: |
          VERSION="${{ steps.version.outputs.tag }}"
          VERSION="${VERSION//v}"
          dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$VERSION-ci.$(date +%Y%m%d%H%M%S) -o nupkg
          
      - name: Upload Artifact
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./nupkg/*.nupkg
        
        
        
      