name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to assign to the release in the format: x.x.x . If not specified, it will automatically assign one based on SemVer and the commit messages since the previous release"
        required: false
      
jobs:
  release-package:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CLINIA_CI_GITHUB_TOKEN }}

      - name: Get new package version, github tag and changelog
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.CLINIA_CI_GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.version }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CLINIA_CI_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}